stages:
  - debug

variables:
  CUSTOM_REGISTRY: "$CUSTOM_REGISTRY"
  CUSTOM_REGISTRY_USER: "$CUSTOM_REGISTRY_USER"
  CUSTOM_REGISTRY_PASSWORD: "$CUSTOM_REGISTRY_PASSWORD"

debug:
  stage: debug
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      alias: docker
  before_script:
    - apk update && apk add git bind-tools  # bind-tools provides nslookup
  script:
    - echo "CUSTOM_REGISTRY: $CUSTOM_REGISTRY"  # Print the value of CUSTOM_REGISTRY
    - nslookup $CUSTOM_REGISTRY  # Check if the domain resolves correctly
    - ping -c 4 $CUSTOM_REGISTRY  # Ping the registry to check connectivity
    - echo "$CUSTOM_REGISTRY_PASSWORD" | docker login -u "$CUSTOM_REGISTRY_USER" --password-stdin $CUSTOM_REGISTRY