# .gitlab-ci.yml

# 빌드 단계 정의
stages:
  - build

# Docker 이미지 빌드 및 푸시 작업
build-and-push:
  stage: build
  image: docker:19.03.12  # Docker 버전
  tags:
    - quickcatch-ci  # 그룹 러너 태그
  variables:
    DOCKER_TLS_CERTDIR: ""  # TLS 인증서 디렉토리 비움
  services:
    - docker:19.03.12-dind  # Docker-in-Docker 서비스
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY  # GitLab Container Registry 로그인
  script:
    - docker build . -t $CI_REGISTRY_IMAGE/my-node-app:${CI_COMMIT_SHORT_SHA}  # Docker 이미지 빌드
    - docker push $CI_REGISTRY_IMAGE/my-node-app:${CI_COMMIT_SHORT_SHA}  # GitLab Container Registry 푸시
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # main 브랜치에 push 이벤트 발생 시 실행

# 다른 작업이나 단계 추가 가능