stages:
  - build

build-and-push:
  stage: build
  image: docker:19.03.12
  variables:
    CUSTOM_REGISTRY: "qkcgitlab.store"
    CUSTOM_REGISTRY_USER: "minho"
    CUSTOM_REGISTRY_PASSWORD: "k8spass#"
    CUSTOM_IMAGE: "my-node-app"
  services:
    - name: docker:19.03.12-dind
      alias: docker
  before_script:
    - docker info  # Docker 데몬이 정상적으로 작동하는지 확인
    - echo "$CUSTOM_REGISTRY_PASSWORD" | docker login -u "$CUSTOM_REGISTRY_USER" --password-stdin $CUSTOM_REGISTRY
  script:
    - docker build -t $CUSTOM_REGISTRY/quickcatch/frontend/runner:1.0 .
    - docker push $CUSTOM_REGISTRY/quickcatch/frontend/runmer:1.0
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
