stages:
  - build

build-and-push:
  stage: build
  image: docker:19.03.12
  services: []
  before_script:
    - docker info  # Docker 데몬이 정상적으로 작동하는지 확인
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/my-node-app:${CI_COMMIT_SHORT_SHA} .
    - docker push $CI_REGISTRY_IMAGE/my-node-app:${CI_COMMIT_SHORT_SHA}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'