stages:
  - build  # 빌드 단계 정의

variables:
  CUSTOM_REGISTRY: "$CUSTOM_REGISTRY"  # 사용자 정의 레지스트리 주소
  CUSTOM_REGISTRY_USER: "$CUSTOM_REGISTRY_USER"  # 사용자 정의 레지스트리 사용자 이름
  CUSTOM_REGISTRY_PASSWORD: "$CUSTOM_REGISTRY_PASSWORD"  # 사용자 정의 레지스트리 비밀번호
  CUSTOM_IMAGE_NAME: "$CUSTOM_IMAGE_NAME"  # 사용자 정의 이미지 이름

build-and-push:
  stage: build  # 빌드 단계에 속하는 작업
  image: docker:19.03.12  # Docker CLI 버전 지정
  services:
    - name: docker:19.03.12-dind  # Docker in Docker (DinD) 서비스 사용
      alias: docker
  before_script:
    - apk update && apk add git
    - docker info  # Docker 데몬이 정상적으로 작동하는지 확인
    - echo "$CUSTOM_REGISTRY_PASSWORD" | docker login -u "$CUSTOM_REGISTRY_USER" --password-stdin $CUSTOM_REGISTRY
    - git clone "https://qkcgitlab.store/quickcatch/infra.git"  # 레지스트리 클론
  script:
    - docker build -t "$CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:$CI_JOB_ID" .  # Docker 이미지 빌드
    - docker push "$CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:$CI_JOB_ID"  # Docker 이미지 푸시
    - |
      sed -i "s|image: $CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:.*|image: $CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:$CI_JOB_ID|g" registry.qkcgitlab.store/quickcatch/infra/qkc-nsp-fro/qkc-app-fro.yaml  # YAML 파일 업데이트
    - cd registry.qkcgitlab.store/quickcatch/infra
    - git add qkc-nsp-fro/qkc-app-fro.yaml
    - git commit -m "Update image tag to $CUSTOM_IMAGE_NAME:$CI_JOB_ID"
    - git push https://qkcgitlab.store/quickcatch/infra.git HEAD:main  # 변경 사항 푸시
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # main 브랜치에서만 실행