stages:
  - build

build-and-push:
  stage: build
  image: docker:19.03.12
  variables:
    DOCKER_HOST: "tcp://docker:2375"  # 도커 호스트 설정
  services:
    - docker:19.03.12  # 도커 서비스
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/my-node-app:${CI_COMMIT_SHORT_SHA} .
    - docker push $CI_REGISTRY_IMAGE/my-node-app:${CI_COMMIT_SHORT_SHA}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'