stages:
  - build

variables:
  CUSTOM_REGISTRY: "$CUSTOM_REGISTRY"
  CUSTOM_REGISTRY_USER: "$CUSTOM_REGISTRY_USER"
  CUSTOM_REGISTRY_PASSWORD: "$CUSTOM_REGISTRY_PASSWORD"
  CUSTOM_IMAGE_NAME: "$CUSTOM_IMAGE_NAME"
  GITLAB_USERNAME: "$GITLAB_USERNAME"
  GITLAB_ACCESS_TOKEN: "$GITLAB_ACCESS_TOKEN"

build-and-push:
  stage: build
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      alias: docker
  before_script:
    - apk update && apk add git bind-tools
    - docker info
    - nslookup $CUSTOM_REGISTRY
    - ping -c 4 $CUSTOM_REGISTRY
    - echo "$CUSTOM_REGISTRY_PASSWORD" | docker login -u "$CUSTOM_REGISTRY_USER" --password-stdin "$CUSTOM_REGISTRY"
    - git config --global credential.helper store
    - echo "https://${GITLAB_USERNAME}:${GITLAB_ACCESS_TOKEN}@qkcgitlab.store" > ~/.git-credentials
    - git config --global user.email "gillhwa9@gmail.com"
    - git config --global user.name "gillhwa"
    - git config --global -l
    - cat ~/.git-credentials
  script:
    - git clone "https://qkcgitlab.store/quickcatch/infra.git"
    - docker build -t "$CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:$CI_JOB_ID" .
    - docker push "$CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:$CI_JOB_ID"
    - cd infra
    - |
      sed -i "s|image: $CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:.*|image: $CUSTOM_REGISTRY/quickcatch/frontend/$CUSTOM_IMAGE_NAME:$CI_JOB_ID|g" qkc-nsp-fro/qkc-app-fro.yaml
    - git add qkc-nsp-fro/qkc-app-fro.yaml
    - git commit -m "Update image tag to $CUSTOM_IMAGE_NAME:$CI_JOB_ID"
    - git push "https://${GITLAB_USERNAME}:${GITLAB_ACCESS_TOKEN}@qkcgitlab.store/quickcatch/infra.git" HEAD:main
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'